config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :blogs

get 'about', to: 'blogs#about'

root "blogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    

    #Rails Uses the concept of DRY that elimenate the redifition of action that's why we can use a private method called in every method we need 

    before_action :find_id, only: [:update,:edit, :destroy,:show]
    def about
    end

    def index 
        @Blog= Blog.all

    end

    def show
    #@Blog = Blog.find(params[:id])
    end

    def new 
    @blog=Blog.new
    end
    
    def create 
     @blog = Blog.create(params.require(:blog).permit(:title, :content))
      if @blog.save
        redirect_to root_path
      else
        render :new
      end
    end

    def edit
     #   @blog = Blog.find(params[:id])
    end

    def update
        @blog = Blog.find(params[:id])
        if @blog.update(params.require(:blog).permit(:title, :content))
            redirect_to root_path
        else
            render :edit
        end
    end

    def destroy
     #@blog = Blog.find(params[:id])
     @blog.destroy
        redirect_to root_path
    end

    private 
    def find_id
        @blog=Blog.find(params[:id])
    end
    

    

end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with model:@blog , local: true do |b| %>

<%= b.text_field :title, class: "form-control" ,placeholder:"Title"%>
<br>
<%= b.text_area :content, class: "form-control", placeholder:"Content" %>
<br>
<%= b.submit%>
<%end %>

app/views/blogs/about.html.erb
<div class="container" id="about_page">
<div class="row">
<div class="col-md-6 offset-3 text-center">
<h1>About</h1>
<p>This App Has Been Released By Boubtane Houssem Eddine 
  Gr33tez To Cyber-Trace Team </p>
</div>  
</div>
</div>

app/views/blogs/edit.html.erb
<div class="container">

<%= render 'form' %>

</div>

app/views/blogs/index.html.erb
<div class="container">
 <div class="row">
   <%  @Blog.each do |single| %>  
   <div class="col-md-4">

   <div class="card" style="width: 18rem;">
     <div class="Card-body">
      <h5 class="card-title"> <%= link_to single.title, blog_path(single) %>  </h5> 
      <p class="card-text"> <%= single.content %></p>
      <%= link_to "view",blog_path(single),class: 'btn btn-outline-primary' %>
      <%= link_to "edit", edit_blog_path(single), class:'btn btn-outline-primary' %>
      <%= link_to "destory", blog_path(single),class:'btn btn-outline-danger ', 
                                         method: :DELETE ,
                                          data:{confirm:'are you sure ?'}%>
     </div>
    </div>
    <br>
    </div>                                          
 <%end%>

 </div>



   
 </div>

app/views/blogs/new.html.erb
<div class="container" id="new_post">
<h1>Add a Blog Post </h1>
<%= render 'form' %>

</div>

app/views/blogs/show.html.erb
<div class="container" id="show_post">
<h1><%= @blog.title%></h1>
<hr>
<p><%= @blog.content%></p>
 <%= link_to "Back", root_path, class: "btn btn-outline-primary" %> 


 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
  <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!--<a class="navbar-brand" href="#">/a>-->
  <%= link_to "HoussemBlogApp",blogs_path,class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">
      <li class="nav-item ">
         <%= link_to "about", about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to "blog",blogs_path, class: 'nav-link'%>
      </li>
      <li class="nav-item active ">
      <%= link_to "add blog post",new_blog_path,class: 'nav-link'%>
      </li>
     
    </ul>
    
  </div>
</nav>